#ifndef APP_ESP8266_H
#define APP_ESP8266_H

#define ESP8266
#define ON 1
#define OFF 0

#define MQTT_TIMEOUT 30
#define MQTT_FLAG_TIMEOUT (MQTT_TIMEOUT * 1000 / portTICK_PERIOD_MS)
#define MQTT_QUEUE_TIMEOUT (MQTT_TIMEOUT * 1000 / portTICK_PERIOD_MS)
#endif /* APP_ESP8266_H */

